require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe TasksController, :type => :controller do

  # This should return the minimal set of attributes required to create a valid
  # Task. As you add validations to Task, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # TasksController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all Tasks as @Tasks" do
      Task = Task.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:Tasks)).to eq([Task])
    end
  end

  describe "GET show" do
    it "assigns the requested Task as @Task" do
      Task = Task.create! valid_attributes
      get :show, {:id => Task.to_param}, valid_session
      expect(assigns(:Task)).to eq(Task)
    end
  end

  describe "GET new" do
    it "assigns a new Task as @Task" do
      get :new, {}, valid_session
      expect(assigns(:Task)).to be_a_new(Task)
    end
  end

  describe "GET edit" do
    it "assigns the requested Task as @Task" do
      Task = Task.create! valid_attributes
      get :edit, {:id => Task.to_param}, valid_session
      expect(assigns(:Task)).to eq(Task)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Task" do
        expect {
          post :create, {:Task => valid_attributes}, valid_session
        }.to change(Task, :count).by(1)
      end

      it "assigns a newly created Task as @Task" do
        post :create, {:Task => valid_attributes}, valid_session
        expect(assigns(:Task)).to be_a(Task)
        expect(assigns(:Task)).to be_persisted
      end

      it "redirects to the created Task" do
        post :create, {:Task => valid_attributes}, valid_session
        expect(response).to redirect_to(Task.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved Task as @Task" do
        post :create, {:Task => invalid_attributes}, valid_session
        expect(assigns(:Task)).to be_a_new(Task)
      end

      it "re-renders the 'new' template" do
        post :create, {:Task => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested Task" do
        Task = Task.create! valid_attributes
        put :update, {:id => Task.to_param, :Task => new_attributes}, valid_session
        Task.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested Task as @Task" do
        Task = Task.create! valid_attributes
        put :update, {:id => Task.to_param, :Task => valid_attributes}, valid_session
        expect(assigns(:Task)).to eq(Task)
      end

      it "redirects to the Task" do
        Task = Task.create! valid_attributes
        put :update, {:id => Task.to_param, :Task => valid_attributes}, valid_session
        expect(response).to redirect_to(Task)
      end
    end

    describe "with invalid params" do
      it "assigns the Task as @Task" do
        Task = Task.create! valid_attributes
        put :update, {:id => Task.to_param, :Task => invalid_attributes}, valid_session
        expect(assigns(:Task)).to eq(Task)
      end

      it "re-renders the 'edit' template" do
        Task = Task.create! valid_attributes
        put :update, {:id => Task.to_param, :Task => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested Task" do
      Task = Task.create! valid_attributes
      expect {
        delete :destroy, {:id => Task.to_param}, valid_session
      }.to change(Task, :count).by(-1)
    end

    it "redirects to the Tasks list" do
      Task = Task.create! valid_attributes
      delete :destroy, {:id => Task.to_param}, valid_session
      expect(response).to redirect_to(Tasks_url)
    end
  end

end
